import logging
from dataclasses import dataclass, field
from typing import Any

import yaml

from .env import settings
from .paths import resolve_config_path

logger = logging.getLogger(__name__)

# YAML config file path for theme
THEME_CONFIG_PATH = resolve_config_path("theme.yaml")


@dataclass
class ThemePalette:
    """Theme palette colors."""

    name: str = "Sage Green"
    primary: str = "#8B9F4F"
    primaryLight: str = "#A4B86C"
    primaryDark: str = "#6B7A3A"
    primarySoft: str = "#B8C78A"
    primaryPale: str = "#D4E0B8"
    accentGold: str = "#D4AF37"
    accentSilver: str = "#B8C5D3"
    # Hero/branding
    heroImage: str | None = None  # URL or path to hero background image
    logoUrl: str | None = None  # URL or path to logo
    faviconUrl: str | None = None  # URL or path to favicon
    appIconUrl: str | None = None  # URL or path to app icon (used in sidebar, etc.)
    # Hero image filters (CSS filter values)
    heroContrast: float | None = None  # 1.0 = normal, 0.8 = less contrast
    heroSaturation: float | None = None  # 1.0 = normal, 0.8 = less saturated
    heroBrightness: float | None = None  # 1.0 = normal, 0.8 = darker
    heroOpacity: float | None = None  # 1.0 = fully visible, 0.5 = semi-transparent
    heroMode: str | None = None  # "dark" (default) or "light"
    # Hero title shimmer gradient colors
    shimmerFrom: str | None = None  # Start color of shimmer sweep (e.g., "#4CD9A0")
    shimmerTo: str | None = None  # End color of shimmer sweep (e.g., "#80D4F0")

    def to_dict(self) -> dict[str, Any]:
        """Convert palette to dict for JSON serialization."""
        return {
            "name": self.name,
            "primary": self.primary,
            "primaryLight": self.primaryLight,
            "primaryDark": self.primaryDark,
            "primarySoft": self.primarySoft,
            "primaryPale": self.primaryPale,
            "accentGold": self.accentGold,
            "accentSilver": self.accentSilver,
            "heroImage": self.heroImage,
            "logoUrl": self.logoUrl,
            "faviconUrl": self.faviconUrl,
            "appIconUrl": self.appIconUrl,
            "heroContrast": self.heroContrast,
            "heroSaturation": self.heroSaturation,
            "heroBrightness": self.heroBrightness,
            "heroOpacity": self.heroOpacity,
            "heroMode": self.heroMode,
            "shimmerFrom": self.shimmerFrom,
            "shimmerTo": self.shimmerTo,
        }


# Default palettes
DEFAULT_PALETTES: dict[str, ThemePalette] = {
    "sage_green": ThemePalette(
        name="Sage Green",
        primary="#8B9F4F",
        primaryLight="#A4B86C",
        primaryDark="#6B7A3A",
        primarySoft="#B8C78A",
        primaryPale="#D4E0B8",
        accentGold="#D4AF37",
        accentSilver="#B8C5D3",
    ),
    "professional_blue": ThemePalette(
        name="Professional Blue",
        primary="#3D5A80",
        primaryLight="#5C7AA3",
        primaryDark="#2B3C73",
        primarySoft="#8BA4C4",
        primaryPale="#C5D4E8",
        accentGold="#D4AF37",
        accentSilver="#B8C5D3",
    ),
}


@dataclass
class BrandingConfig:
    """Branding text used throughout the application."""

    app_name: str = "AXIS"
    tagline: str = "AI Evaluation Platform"
    subtitle: str = "The AI Evaluation Studio"
    description: str = "Agent X-ray Interface & Statistics"
    report_footer: str = "Report generated by AXIS AI Evaluation Platform"
    docs_url: str = "https://ax-foundry.github.io/axis/"
    footer_name: str = ""
    footer_icon: str = ""

    def to_dict(self) -> dict[str, Any]:
        """Convert to dict for JSON serialization."""
        return {
            "app_name": self.app_name,
            "tagline": self.tagline,
            "subtitle": self.subtitle,
            "description": self.description,
            "report_footer": self.report_footer,
            "docs_url": self.docs_url,
            "footer_name": self.footer_name or self.app_name,
            "footer_icon": self.footer_icon or None,
        }


@dataclass
class ThemeConfig:
    """Theme configuration loaded from YAML or env vars."""

    active: str = "professional_blue"
    palettes: dict[str, ThemePalette] = field(default_factory=lambda: dict(DEFAULT_PALETTES))
    branding: BrandingConfig = field(default_factory=BrandingConfig)

    def get_active_palette(self) -> ThemePalette:
        """Get the currently active palette."""
        return self.palettes.get(self.active, self.palettes.get("sage_green", ThemePalette()))

    def to_dict(self) -> dict[str, Any]:
        """Convert config to dict for JSON serialization."""
        return {
            "active": self.active,
            "palettes": {name: palette.to_dict() for name, palette in self.palettes.items()},
            "branding": self.branding.to_dict(),
        }


def load_theme_config() -> ThemeConfig:
    """Load theme configuration from YAML file first, then env vars.

    Env vars can override individual colors.
    """
    config = ThemeConfig()

    # Try loading from YAML config file first
    if THEME_CONFIG_PATH.exists():
        try:
            with THEME_CONFIG_PATH.open() as f:
                yaml_config: dict[str, Any] = yaml.safe_load(f) or {}

            if yaml_config.get("theme"):
                theme_data = yaml_config["theme"]

                # Load active palette name
                if theme_data.get("active"):
                    config.active = theme_data["active"]

                # Load custom palettes
                if theme_data.get("palettes"):
                    for palette_name, palette_data in theme_data["palettes"].items():
                        config.palettes[palette_name] = ThemePalette(
                            name=palette_data.get("name", palette_name),
                            primary=palette_data.get("primary", "#8B9F4F"),
                            primaryLight=palette_data.get("primaryLight", "#A4B86C"),
                            primaryDark=palette_data.get("primaryDark", "#6B7A3A"),
                            primarySoft=palette_data.get("primarySoft", "#B8C78A"),
                            primaryPale=palette_data.get("primaryPale", "#D4E0B8"),
                            accentGold=palette_data.get("accentGold", "#D4AF37"),
                            accentSilver=palette_data.get("accentSilver", "#B8C5D3"),
                            heroImage=palette_data.get("heroImage"),
                            logoUrl=palette_data.get("logoUrl"),
                            faviconUrl=palette_data.get("faviconUrl"),
                            appIconUrl=palette_data.get("appIconUrl"),
                            heroContrast=palette_data.get("heroContrast"),
                            heroSaturation=palette_data.get("heroSaturation"),
                            heroBrightness=palette_data.get("heroBrightness"),
                            heroOpacity=palette_data.get("heroOpacity"),
                            heroMode=palette_data.get("heroMode"),
                            shimmerFrom=palette_data.get("shimmerFrom"),
                            shimmerTo=palette_data.get("shimmerTo"),
                        )

                # Load branding config
                if theme_data.get("branding"):
                    branding_data = theme_data["branding"]
                    config.branding = BrandingConfig(
                        app_name=branding_data.get("app_name", "AXIS"),
                        tagline=branding_data.get("tagline", "AI Evaluation Platform"),
                        subtitle=branding_data.get("subtitle", "The AI Evaluation Studio"),
                        description=branding_data.get(
                            "description", "Agent X-ray Interface & Statistics"
                        ),
                        report_footer=branding_data.get(
                            "report_footer",
                            "Report generated by AXIS AI Evaluation Platform",
                        ),
                        docs_url=branding_data.get(
                            "docs_url",
                            "https://ax-foundry.github.io/axis/",
                        ),
                        footer_name=branding_data.get("footer_name", ""),
                        footer_icon=branding_data.get("footer_icon", ""),
                    )

                logger.info(f"Loaded theme config from {THEME_CONFIG_PATH}")
        except Exception as e:
            logger.warning(f"Failed to load theme YAML config: {e}")

    # Override with env vars if set
    if settings.axis_theme_active:
        config.active = settings.axis_theme_active
        logger.info(f"Theme active palette overridden by env: {config.active}")

    # If individual color env vars are set, create/modify the active palette
    # Check if any env override is set
    has_overrides = any(
        v is not None
        for v in [
            settings.axis_theme_primary,
            settings.axis_theme_primary_light,
            settings.axis_theme_primary_dark,
            settings.axis_theme_primary_soft,
            settings.axis_theme_primary_pale,
            settings.axis_theme_accent_gold,
            settings.axis_theme_accent_silver,
            settings.axis_theme_hero_image,
            settings.axis_theme_logo_url,
            settings.axis_theme_favicon_url,
            settings.axis_theme_app_icon_url,
            settings.axis_theme_hero_contrast,
            settings.axis_theme_hero_saturation,
            settings.axis_theme_hero_brightness,
            settings.axis_theme_hero_opacity,
            settings.axis_theme_hero_mode,
        ]
    )

    if has_overrides:
        # Get current active palette as base
        base_palette = config.get_active_palette()

        # Create new palette with overrides (access settings directly for type safety)
        config.palettes[config.active] = ThemePalette(
            name=base_palette.name,
            primary=settings.axis_theme_primary or base_palette.primary,
            primaryLight=settings.axis_theme_primary_light or base_palette.primaryLight,
            primaryDark=settings.axis_theme_primary_dark or base_palette.primaryDark,
            primarySoft=settings.axis_theme_primary_soft or base_palette.primarySoft,
            primaryPale=settings.axis_theme_primary_pale or base_palette.primaryPale,
            accentGold=settings.axis_theme_accent_gold or base_palette.accentGold,
            accentSilver=settings.axis_theme_accent_silver or base_palette.accentSilver,
            heroImage=settings.axis_theme_hero_image or base_palette.heroImage,
            logoUrl=settings.axis_theme_logo_url or base_palette.logoUrl,
            faviconUrl=settings.axis_theme_favicon_url or base_palette.faviconUrl,
            appIconUrl=settings.axis_theme_app_icon_url or base_palette.appIconUrl,
            heroContrast=settings.axis_theme_hero_contrast
            if settings.axis_theme_hero_contrast is not None
            else base_palette.heroContrast,
            heroSaturation=settings.axis_theme_hero_saturation
            if settings.axis_theme_hero_saturation is not None
            else base_palette.heroSaturation,
            heroBrightness=settings.axis_theme_hero_brightness
            if settings.axis_theme_hero_brightness is not None
            else base_palette.heroBrightness,
            heroOpacity=settings.axis_theme_hero_opacity
            if settings.axis_theme_hero_opacity is not None
            else base_palette.heroOpacity,
            heroMode=settings.axis_theme_hero_mode or base_palette.heroMode,
            shimmerFrom=base_palette.shimmerFrom,
            shimmerTo=base_palette.shimmerTo,
        )
        logger.info("Theme palette overridden by environment variables")

    return config


# Global theme config instance
theme_config = load_theme_config()
