import logging
from dataclasses import asdict, dataclass, field, fields
from typing import Any

import yaml

from .env import settings
from .paths import resolve_config_path

logger = logging.getLogger(__name__)

# YAML config file path for theme
THEME_CONFIG_PATH = resolve_config_path("theme.yaml")


@dataclass
class ThemePalette:
    """Theme palette colors."""

    name: str = "Sage Green"
    primary: str = "#8B9F4F"
    primaryLight: str = "#A4B86C"
    primaryDark: str = "#6B7A3A"
    primarySoft: str = "#B8C78A"
    primaryPale: str = "#D4E0B8"
    accentGold: str = "#D4AF37"
    accentSilver: str = "#B8C5D3"
    # Hero/branding
    heroImage: str | None = None  # URL or path to hero background image
    logoUrl: str | None = None  # URL or path to logo
    faviconUrl: str | None = None  # URL or path to favicon
    appIconUrl: str | None = None  # URL or path to app icon (used in sidebar, etc.)
    # Hero image filters (CSS filter values)
    heroContrast: float | None = None  # 1.0 = normal, 0.8 = less contrast
    heroSaturation: float | None = None  # 1.0 = normal, 0.8 = less saturated
    heroBrightness: float | None = None  # 1.0 = normal, 0.8 = darker
    heroOpacity: float | None = None  # 1.0 = fully visible, 0.5 = semi-transparent
    heroMode: str | None = None  # "dark" (default) or "light"
    # Hero title shimmer gradient colors
    shimmerFrom: str | None = None  # Start color of shimmer sweep (e.g., "#4CD9A0")
    shimmerTo: str | None = None  # End color of shimmer sweep (e.g., "#80D4F0")

    def to_dict(self) -> dict[str, Any]:
        """Convert palette to dict for JSON serialization."""
        return asdict(self)

    @classmethod
    def from_yaml(cls, data: dict[str, Any], fallback_name: str = "") -> "ThemePalette":
        """Create a ThemePalette from YAML dict, ignoring unknown keys."""
        defaults = cls()
        known = {f.name for f in fields(cls)}
        kwargs: dict[str, Any] = {"name": data.get("name", fallback_name or defaults.name)}
        for key in known:
            if key == "name":
                continue
            if key in data:
                kwargs[key] = data[key]
        return cls(**kwargs)


# Default palettes
DEFAULT_PALETTES: dict[str, ThemePalette] = {
    "sage_green": ThemePalette(
        name="Sage Green",
        primary="#8B9F4F",
        primaryLight="#A4B86C",
        primaryDark="#6B7A3A",
        primarySoft="#B8C78A",
        primaryPale="#D4E0B8",
        accentGold="#D4AF37",
        accentSilver="#B8C5D3",
    ),
    "professional_blue": ThemePalette(
        name="Professional Blue",
        primary="#3D5A80",
        primaryLight="#5C7AA3",
        primaryDark="#2B3C73",
        primarySoft="#8BA4C4",
        primaryPale="#C5D4E8",
        accentGold="#D4AF37",
        accentSilver="#B8C5D3",
    ),
}


@dataclass
class BrandingConfig:
    """Branding text used throughout the application."""

    app_name: str = "AXIS"
    tagline: str = "AI Evaluation Platform"
    subtitle: str = "The AI Evaluation Studio"
    description: str = "Agent X-ray Interface & Statistics"
    report_footer: str = "Report generated by AXIS AI Evaluation Platform"
    docs_url: str = "https://ax-foundry.github.io/axis/"
    footer_name: str = ""
    footer_icon: str = ""

    def to_dict(self) -> dict[str, Any]:
        """Convert to dict for JSON serialization."""
        d = asdict(self)
        d["footer_name"] = self.footer_name or self.app_name
        d["footer_icon"] = self.footer_icon or None
        return d

    @classmethod
    def from_yaml(cls, data: dict[str, Any]) -> "BrandingConfig":
        """Create a BrandingConfig from YAML dict, ignoring unknown keys."""
        known = {f.name for f in fields(cls)}
        kwargs = {k: v for k, v in data.items() if k in known}
        return cls(**kwargs)


@dataclass
class ThemeConfig:
    """Theme configuration loaded from YAML or env vars."""

    active: str = "professional_blue"
    palettes: dict[str, ThemePalette] = field(default_factory=lambda: dict(DEFAULT_PALETTES))
    branding: BrandingConfig = field(default_factory=BrandingConfig)

    def get_active_palette(self) -> ThemePalette:
        """Get the currently active palette."""
        return self.palettes.get(self.active, self.palettes.get("sage_green", ThemePalette()))

    def to_dict(self) -> dict[str, Any]:
        """Convert config to dict for JSON serialization."""
        return {
            "active": self.active,
            "palettes": {name: palette.to_dict() for name, palette in self.palettes.items()},
            "branding": self.branding.to_dict(),
        }


# Mapping from env var settings attributes to ThemePalette field names.
# Only fields with env var overrides are listed here.
_ENV_OVERRIDES: dict[str, str] = {
    "axis_theme_primary": "primary",
    "axis_theme_primary_light": "primaryLight",
    "axis_theme_primary_dark": "primaryDark",
    "axis_theme_primary_soft": "primarySoft",
    "axis_theme_primary_pale": "primaryPale",
    "axis_theme_accent_gold": "accentGold",
    "axis_theme_accent_silver": "accentSilver",
    "axis_theme_hero_image": "heroImage",
    "axis_theme_logo_url": "logoUrl",
    "axis_theme_favicon_url": "faviconUrl",
    "axis_theme_app_icon_url": "appIconUrl",
    "axis_theme_hero_contrast": "heroContrast",
    "axis_theme_hero_saturation": "heroSaturation",
    "axis_theme_hero_brightness": "heroBrightness",
    "axis_theme_hero_opacity": "heroOpacity",
    "axis_theme_hero_mode": "heroMode",
}


def load_theme_config() -> ThemeConfig:
    """Load theme configuration from YAML file first, then env vars.

    Env vars can override individual colors.
    """
    config = ThemeConfig()

    # Try loading from YAML config file first
    if THEME_CONFIG_PATH.exists():
        try:
            with THEME_CONFIG_PATH.open() as f:
                yaml_config: dict[str, Any] = yaml.safe_load(f) or {}

            if yaml_config.get("theme"):
                theme_data = yaml_config["theme"]

                # Load active palette name
                if theme_data.get("active"):
                    config.active = theme_data["active"]

                # Load custom palettes
                if theme_data.get("palettes"):
                    for palette_name, palette_data in theme_data["palettes"].items():
                        config.palettes[palette_name] = ThemePalette.from_yaml(
                            palette_data, fallback_name=palette_name
                        )

                # Load branding config
                if theme_data.get("branding"):
                    config.branding = BrandingConfig.from_yaml(theme_data["branding"])

                logger.info(f"Loaded theme config from {THEME_CONFIG_PATH}")
        except Exception as e:
            logger.warning(f"Failed to load theme YAML config: {e}")

    # Override with env vars if set
    if settings.axis_theme_active:
        config.active = settings.axis_theme_active
        logger.info(f"Theme active palette overridden by env: {config.active}")

    # Collect env overrides into a dict of {palette_field: value}
    overrides: dict[str, Any] = {}
    for settings_attr, palette_field in _ENV_OVERRIDES.items():
        val = getattr(settings, settings_attr, None)
        if val is not None:
            overrides[palette_field] = val

    if overrides:
        base = asdict(config.get_active_palette())
        base.update(overrides)
        config.palettes[config.active] = ThemePalette(**base)
        logger.info("Theme palette overridden by environment variables")

    return config


# Global theme config instance
theme_config = load_theme_config()
