import { create } from 'zustand';

import { DefaultColors } from '@/types';

import type { BrandingConfig, ThemePalette } from '@/types';

const defaultBranding: BrandingConfig = {
  app_name: 'AXIS',
  tagline: 'AI Evaluation Platform',
  subtitle: 'The AI Evaluation Studio',
  description: 'Agent X-ray Interface & Statistics',
  report_footer: 'Report generated by AXIS AI Evaluation Platform',
  docs_url: 'https://ax-foundry.github.io/axis/',
  footer_name: 'AXIS',
  footer_icon: null,
};

interface ThemeState {
  // State
  isLoaded: boolean;
  isLoading: boolean;
  error: string | null;
  activePaletteName: string;
  palette: ThemePalette;
  availablePalettes: Record<string, ThemePalette>;
  branding: BrandingConfig;

  // Actions
  setTheme: (
    active: string,
    activePalette: ThemePalette,
    palettes: Record<string, ThemePalette>,
    branding?: BrandingConfig
  ) => void;
  setLoading: (loading: boolean) => void;
  setError: (error: string | null) => void;
  applyPalette: (palette: ThemePalette) => void;
}

/**
 * Convert hex color to RGB values string (e.g., "#8B9F4F" -> "139 159 79")
 */
function hexToRgb(hex: string): string {
  // Remove # if present
  const cleanHex = hex.replace('#', '');

  // Parse hex values
  const r = parseInt(cleanHex.substring(0, 2), 16);
  const g = parseInt(cleanHex.substring(2, 4), 16);
  const b = parseInt(cleanHex.substring(4, 6), 16);

  return `${r} ${g} ${b}`;
}

/**
 * Apply theme palette colors as CSS custom properties on :root
 */
function applyCSSVariables(palette: ThemePalette): void {
  if (typeof document === 'undefined') return;

  const root = document.documentElement;

  // Set hex values for direct use
  root.style.setProperty('--primary', palette.primary);
  root.style.setProperty('--primary-light', palette.primaryLight);
  root.style.setProperty('--primary-dark', palette.primaryDark);
  root.style.setProperty('--primary-soft', palette.primarySoft);
  root.style.setProperty('--primary-pale', palette.primaryPale);
  root.style.setProperty('--accent-gold', palette.accentGold);
  root.style.setProperty('--accent-silver', palette.accentSilver);

  // Set RGB values for Tailwind opacity support
  root.style.setProperty('--primary-rgb', hexToRgb(palette.primary));
  root.style.setProperty('--primary-light-rgb', hexToRgb(palette.primaryLight));
  root.style.setProperty('--primary-dark-rgb', hexToRgb(palette.primaryDark));
  root.style.setProperty('--primary-soft-rgb', hexToRgb(palette.primarySoft));
  root.style.setProperty('--primary-pale-rgb', hexToRgb(palette.primaryPale));
  root.style.setProperty('--accent-gold-rgb', hexToRgb(palette.accentGold));
  root.style.setProperty('--accent-silver-rgb', hexToRgb(palette.accentSilver));

  // Set hero image if provided
  if (palette.heroImage) {
    root.style.setProperty('--hero-image', `url(${palette.heroImage})`);
  } else {
    root.style.removeProperty('--hero-image');
  }

  // Set logo URL if provided
  if (palette.logoUrl) {
    root.style.setProperty('--logo-url', `url(${palette.logoUrl})`);
  } else {
    root.style.removeProperty('--logo-url');
  }

  // Build hero image filter string from individual properties
  const filterParts: string[] = [];
  if (palette.heroContrast != null) {
    filterParts.push(`contrast(${palette.heroContrast})`);
  }
  if (palette.heroSaturation != null) {
    filterParts.push(`saturate(${palette.heroSaturation})`);
  }
  if (palette.heroBrightness != null) {
    filterParts.push(`brightness(${palette.heroBrightness})`);
  }

  if (filterParts.length > 0) {
    root.style.setProperty('--hero-filter', filterParts.join(' '));
  } else {
    root.style.removeProperty('--hero-filter');
  }

  // Set hero opacity if provided
  if (palette.heroOpacity != null) {
    root.style.setProperty('--hero-opacity', String(palette.heroOpacity));
  } else {
    root.style.removeProperty('--hero-opacity');
  }
}

// Default palette from DefaultColors
const defaultPalette: ThemePalette = {
  name: 'Professional Blue',
  primary: DefaultColors.primary,
  primaryLight: DefaultColors.primaryLight,
  primaryDark: DefaultColors.primaryDark,
  primarySoft: DefaultColors.primarySoft,
  primaryPale: DefaultColors.primaryPale,
  accentGold: DefaultColors.accentGold,
  accentSilver: DefaultColors.accentSilver,
  heroImage: null,
  logoUrl: null,
  faviconUrl: null,
  appIconUrl: null,
  heroContrast: null,
  heroSaturation: null,
  heroBrightness: null,
  heroOpacity: null,
};

export const useThemeStore = create<ThemeState>((set) => ({
  // Initial state
  isLoaded: false,
  isLoading: false,
  error: null,
  activePaletteName: 'professional_blue',
  palette: defaultPalette,
  availablePalettes: {
    professional_blue: defaultPalette,
  },
  branding: defaultBranding,

  // Actions
  setTheme: (active, activePalette, palettes, branding) => {
    // Apply CSS variables
    applyCSSVariables(activePalette);

    set({
      isLoaded: true,
      isLoading: false,
      error: null,
      activePaletteName: active,
      palette: activePalette,
      availablePalettes: palettes,
      branding: branding ?? defaultBranding,
    });
  },

  setLoading: (isLoading) => set({ isLoading }),

  setError: (error) => set({ error, isLoading: false }),

  applyPalette: (palette) => {
    applyCSSVariables(palette);
    set({ palette });
  },
}));
